sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t xhavier4/front-end -f Dockerfile.dev .

script:
  - docker run -e CI=true xhavier4/front-end npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'front-end'
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-us-east-2-065759357371'
  bucket_path: 'front-end'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


