sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t javiergatto/front-end -f Dockerfile.dev .

script:
  - docker run -e CI=true javiergatto/front-end npm run test
